global:
  auth_dir: .
  data_dir: .
  out_dir: .

cloud:
  aws:
    ca_certs: root-CA.crt
    client_id:
    device_cert:
    device_private_key:
    host:
    port: 8883
  gcloud:
    algorithm: RS256
    ca_certs: google_CA_roots.pem
    cloud_region: europe-west1
    device_id:
    device_private_key:
    host: mqtt.googleapis.com
    jwt_expires_minutes: 15
    port: 8883
    project_id: home-use-pattern-study
    registry_id: rtls-tags

publish:
  jwt_expires_minutes: 15

pull:
  service_account_json:

tracking:
  check_period: 12
  interval: 1
  pos_algo: POSITIONING_ALGORITHM_UWB_ONLY
  pos_dim: 3
  timeout: 1
  wait_time: 0.5
