global:
  data_dir: .
  out_dir: .

publish:
  algorithm: RS256
  ca_certs: auth/google_CA_roots.pem
  cloud_region: europe-west1
  device_id:
  jwt_expires_minutes: 15
  mqtt_bridge_hostname: mqtt.googleapis.com
  mqtt_bridge_port: 8883
  private_key_file: auth/rsa_gcloud_private.pem
  project_id: home-use-pattern-study
  registry_id: rtls-tags

tracking:
  pos_algo: POSITIONING_ALGORITHM_UWB_ONLY
  pos_dim: DIMENSION_3D
